sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "10.4.1"
before_script:
  - yarn build
  - yarn start
  - sleep 3
script: yarn test
git:
  depth: 1