sudo: false
language: node_js
cache:
  directories:
    - node_modules
  yarn: true
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
notifications:
  email: false
node_js:
  - "10.4.1"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.9 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CFLAGS="$CFLAGS -std=c99" ; fi
before_script: bash script/test.sh
script: yarn test
git:
  depth: 1
